main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix="/clientes")

if __name__ == "__main__":
    app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

cliente_route = Blueprint("cliente", __name__)

@cliente_route.route("/") # Listar todos os clientes
def lista_clientes():
    return render_template("lista_clientes.html", clientes=CLIENTES)


@cliente_route.route("/", methods=["POST"]) # Inserir os dados do cliente.
def inserir_cliente():
    
    nome = request.form.get('nome')    
    email = request.form.get('email')
    
    CLIENTES.append( { "nome": nome,
                      "email": email } )
    
    return redirect(url_for('cliente.lista_clientes'))


@cliente_route.route("/new") # Formulário para cadastrar um cliente.
def form_cliente():
    return render_template("form_cliente.html")


@cliente_route.route("/<int:cliente_id>") # Exibir detalhes do cliente.
def detalhe_cliente(cliente_id):
    return render_template("detalhe_cliente.html")


@cliente_route.route("/<int:cliente_id>/edit") # Formulário para editar um cliente.
def form_edit_cliente(cliente_id):
    return render_template("form_edit_cliente.html")


@cliente_route.route("/<int:cliente_id>/update", methods=["PUT"]) # Atualizar informações de um cliente.
def atualizar_cliente(cliente_id):
    pass


@cliente_route.route("/<int:cliente_id>/delete", methods=["DELETE"]) # Deletar um cliente.
def deletar_cliente(cliente_id):
    pass

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint("home", __name__)

@home_route.route("/")
def home():
    return render_template("index.html")

templates/form_cliente.html
<form class="c-form" action=" {{ url_for('cliente.inserir_cliente')}}" method="POST">

    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome">
    </div>

    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="text" class="form-control" name="email">
    </div>

    <button type="submit" class="btn btn-primary">ADICIONAR CLIENTE</button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
  </head>
  <body>

    <h1 class="text-center">Gestão de clientes</h1>

    <div class="container">
      <!-- Formulário para adicionar um cliente -->
      <div c-container="{{ url_for('cliente.form_cliente') }}"></div>

      <!-- Lista de clientes -->
      <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
  </body>
</html>

templates/lista_clientes.html
<table class="table">
    <thead>

      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>

    </thead>
    <tbody>

      {% for cliente in clientes %}
        
      <tr>
        <th scope="row">{{ cliente.id }}</th>
        <td>{{ cliente.nome }}</td>
        <td> {{ cliente.email }}</td>
        <td>
          <button class="btn btn-primary">EDITAR</button>
          <button class="btn btn-danger">DELETAR</button>
        </td>
      </tr>

      {% endfor %}
     
    </tbody>
  </table>

templates/sobre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sobre</title>
</head>
<body>
    <h1>SOBRE MIM</h1>
</body>
</html> 